### ISSUE TITLE
Difficult to see latest transactions

### ISSUE THREAD

**Issue by mustardpower** [franky47/centralized-coin-explorer#3]
Now there are a fair few transactions that have taken place, it takes a long while to navigate to the last transaction page.

Would recommend either reversing the order that the transactions are displayed or adding buttons to the PageNavigation component to go to the first and last page.

**Comment by franky47** [comment]
The total transaction count can be obtained by GETting `https://www.centralized-coin.com/api/stats`, and knowing there are 50 transactions per page, this would allow calculating the last page number.

Would you like to open a PR ? This would award you 500cc.
